"""length column name change

Revision ID: 0bbc59f15b23
Revises: 47a8ae5f8047
Create Date: 2024-05-08 00:05:54.157903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbc59f15b23'
down_revision = '47a8ae5f8047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=True))
        batch_op.drop_column('lenght')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenght', sa.INTEGER(), nullable=True))
        batch_op.drop_column('length')

    # ### end Alembic commands ###
